version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
branches:
  only:
    - master
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test:
  categories:
    only:
    - Unit
deploy:
- provider: NuGet
  api_key:
    secure: 8GQgV2DHU3qdilEMg9OZqXx6RfeZUVWjsbXgj1b8xP4lqY4Xrn4fY/wMriMI7HN0